workflows:
  ios-free-build:
    name: iOS Free Tier Build
    max_build_duration: 60
    triggering:
      events:
        - push
      branch_patterns:
        - pattern: main
          include: true
          source: true
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Install Dependencies
        script: |
          flutter pub get
          cd ios
          pod install
          cd ..
      - name: Build iOS IPA (No Signing)
        script: |
          flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
